apiVersion: v1
kind: Namespace
metadata:
  name: customer
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          # image: localhost:5000/customer-service:0.1
          image: customer:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: customer
  labels:
    app: customer
spec:
  type: ClusterIP 
  selector:
    app: customer
  ports:
    - name: http
      protocol: TCP
      port: 8080

---
# Enable when you want to test ingress functionality
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: customer-ingress
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /customer
#         backend:
#           serviceName: customer-service
#           servicePort: 8501